executable = "../software-analysis-plasma-plugins/examples/swifi_secret_code/hello"
function = "main"

[simulator]
name = "gdb"

[simulator.options]
CF = false
OF = false
STACK_M = false
gdb_path = "/usr/bin/gdb"

[variables]
